### ISSUE TITLE
old release disappeared

### ISSUE THREAD

**Issue by biot** [StdCarrot/Py3AMF#14]
I see a new release (0.8.11) of Py3AMF is available on PyPI. However the older 0.8.10 is no longer available for download there. The problem is that external projects depend on it, namely oe-alliance-core, the basis of a ton of satellite receiver set top boxes. That build is now broken. Is there any way you could put 0.8.10 on PyPI again, until things in openoe-alliance catch up?

Incidentally, there's no 0.8.11 on your github either.

**Comment by StdCarrot** [comment]
0.8.10 is installed correctly with PyPi when I tested.(See the below image)

Anyway, I'll release 0.8.11 on GitHub ASAP.


<img width="673" alt="image" src="https://user-images.githubusercontent.com/1968929/222897164-1091c625-47df-454e-b1c5-80866b8edfce.png">

**Comment by biot** [comment]
Hmm, the tarball seems to have appeared again, and the build now works again.

Thanks for the prompt response.
