### ISSUE TITLE
Release version 0.8.7 in PyPi

### ISSUE THREAD

**Issue by pauloAmaral** [StdCarrot/Py3AMF#5]
It would be great if version 0.8.7 was available in PyPi, since the http header fix is really import for me.

**Comment by StdCarrot** [comment]
It was already published.
Try `pip3 search py3amf` then you may get `Py3AMF (0.8.7)  - AMF support for Python` in console. 
If you already installed py3amf, use `pip3 install -U py3amf` to upgrade.

**Comment by pauloAmaral** [comment]
Ok, thank you, didn't notice it was already there. Thanks for the response :)
